`include "../macros.vh"

module MMU #(
    parameter TLB_ENTRIES = 16
) (
    input  wire                                 clk,
    input  wire [`TLB_OP_INVALID:`TLB_OP_WRITE] TLB_wfi_op,
    input  wire [              `VPPN_WIDTH-1:0] invtlb_vppn,
    input  wire [                          9:0] invtlb_asid,
    input  wire [                          4:0] invtlb_op,
    input  wire [      $clog2(TLB_ENTRIES)-1:0] TLB_rw_index,
    input  wire [      $clog2(TLB_ENTRIES)-1:0] TLB_w_random,
    input  wire [            `TLBEHI_WIDTH-1:0] TLB_sw_hi,
    input  wire [            `TLBELO_WIDTH-1:0] TLB_w_lo0,
    input  wire [            `TLBELO_WIDTH-1:0] TLB_w_lo1,
    output wire [      $clog2(TLB_ENTRIES)-1:0] TLB_s_index,
    output wire                                 TLB_s_found,
    output wire [            `TLBEHI_WIDTH-1:0] TLB_r_hi,
    output wire [            `TLBELO_WIDTH-1:0] TLB_r_lo0,
    output wire [            `TLBELO_WIDTH-1:0] TLB_r_lo1
);
    TLB #(
        .TLB_ENTRIES(TLB_ENTRIES)
    ) TLB_inst (
        .clk        (clk),
        .s_vppn     (TLB_sw_hi[`TLBEHI_VPPN]),
        .s_asid     (TLB_sw_hi[`TLBEHI_ASID]),
        .s_found    (TLB_s_found),
        .s_index    (TLB_s_index),
        .r_index    (TLB_rw_index),
        .r_vppn     (TLB_r_hi[`TLBEHI_VPPN]),
        .r_ps       (TLB_r_hi[`TLBEHI_PS]),
        .r_g        (TLB_r_hi[`TLBEHI_G]),
        .r_asid     (TLB_r_hi[`TLBEHI_ASID]),
        .r_e        (TLB_r_hi[`TLBEHI_E]),
        .r_ppn0     (TLB_r_lo0[`TLBELO_PPN]),
        .r_plv0     (TLB_r_lo0[`TLBELO_PLV]),
        .r_mat0     (TLB_r_lo0[`TLBELO_MAT]),
        .r_d0       (TLB_r_lo0[`TLBELO_D]),
        .r_v0       (TLB_r_lo0[`TLBELO_V]),
        .r_ppn1     (TLB_r_lo1[`TLBELO_PPN]),
        .r_plv1     (TLB_r_lo1[`TLBELO_PLV]),
        .r_mat1     (TLB_r_lo1[`TLBELO_MAT]),
        .r_d1       (TLB_r_lo1[`TLBELO_D]),
        .r_v1       (TLB_r_lo1[`TLBELO_V]),
        .we         (TLB_wfi_op[`TLB_OP_WRITE] | TLB_wfi_op[`TLB_OP_FILL]),
        .w_index    (TLB_operation[`TLB_OP_FILL] ? TLB_w_random : TLB_rw_index),
        .w_vppn     (TLB_sw_hi[`TLBEHI_VPPN]),
        .w_ps       (TLB_sw_hi[`TLBEHI_PS]),
        .w_g        (TLB_sw_hi[`TLBEHI_G]),
        .w_asid     (TLB_sw_hi[`TLBEHI_ASID]),
        .w_e        (TLB_sw_hi[`TLBEHI_E]),
        .w_ppn0     (TLB_w_lo0[`TLBELO_PPN]),
        .w_plv0     (TLB_w_lo0[`TLBELO_PLV]),
        .w_mat0     (TLB_w_lo0[`TLBELO_MAT]),
        .w_d0       (TLB_w_lo0[`TLBELO_D]),
        .w_v0       (TLB_w_lo0[`TLBELO_V]),
        .w_ppn1     (TLB_w_lo1[`TLBELO_PPN]),
        .w_plv1     (TLB_w_lo1[`TLBELO_PLV]),
        .w_mat1     (TLB_w_lo1[`TLBELO_MAT]),
        .w_d1       (TLB_w_lo1[`TLBELO_D]),
        .w_v1       (TLB_w_lo1[`TLBELO_V]),
        .invtlb_en  (TLB_wfi_op[`TLB_OP_INVALID]),
        .invtlb_op  (invtlb_op),
        .invtlb_vppn(invtlb_vppn),
        .invtlb_asid(invtlb_asid),
        .s0_vppn    (),
        .s0_va_bit12(),
        .s0_asid    (),
        .s0_found   (),
        .s0_index   (),
        .s0_ps      (),
        .s0_ppn     (),
        .s0_plv     (),
        .s0_mat     (),
        .s0_d       (),
        .s0_v       (),
        .s1_vppn    (),
        .s1_va_bit12(),
        .s1_asid    (),
        .s1_found   (),
        .s1_index   (),
        .s1_ps      (),
        .s1_ppn     (),
        .s1_plv     (),
        .s1_mat     (),
        .s1_d       (),
        .s1_v       ()
    );
endmodule
